Fixes to threads

diff --git a/Make/makefile.include b/Make/makefile.include
--- a/Make/makefile.include
+++ b/Make/makefile.include
@@ -175,6 +175,17 @@ ifndef VALGRIND_OPTIONS
     VALGRIND_OPTIONS+=--fullpath-after=
 endif
 
+ifndef HELGRIND_OPTIONS
+    # Use the tread-debugging tool
+    HELGRIND_OPTIONS=--tool=helgrind
+    # Report an error if thread 1 reads XXXX, thread 2 frees it, and no lock prevents a race
+    HELGRIND_OPTIONS+=--free-is-write=yes
+    # Should run silently for regression tests, only report errors
+    # For easy debugging
+    HELGRIND__OPTIONS+=--fullpath-after=
+endif
+
+
 ifndef GDB_OPTIONS
    # Use terminal user interface (display source code)
    GDB_OPTIONS=-tui 
@@ -320,6 +331,9 @@ ifdef BUILD_TIME_TESTS
    ifeq ($(findstring memtest,$(MAKECMDGOALS)),memtest)
 	   testCmd=VALGRIND_AUTO_TESTS
    endif
+   ifeq ($(findstring threadtest,$(MAKECMDGOALS)),threadtest)
+	   testCmd=HELGRIND_AUTO_TESTS
+   endif
    ifeq ($(findstring gdbtest,$(MAKECMDGOALS)),gdbtest)
 	   testCmd=GDB_AUTO_TESTS
    endif
@@ -407,6 +421,7 @@ endif
 
 all: $(BUILD_DEPS) $(TO_COPY) $(POST_BUILD_DEPS)
 memtest: all
+threadtest: all
 gdbtest: all
 cover: all 
 profile: all
@@ -470,6 +485,14 @@ VALGRIND_AUTO_TESTS: BUILD_AUTO_TESTS
 		echo "***********************************************************"; \
 		echo "Running auto test: $$test";\
 		    valgrind $(VALGRIND_OPTIONS) $$test || exit;\
+		echo "************************************************************"; \
+	done
+
+HELGRIND_AUTO_TESTS: BUILD_AUTO_TESTS
+	@for test in $(TESTS_TO_RUN); do \
+		echo "***********************************************************"; \
+		echo "Running auto test: $$test";\
+		    valgrind $(HELGRIND_OPTIONS) $$test || exit;\
 		echo "************************************************************"; \
 	done
 
